### ISSUE TITLE
ImportError: No module named 'botan'

### ISSUE THREAD

**Issue by williamjmorenor** [Antidote1911/cryptoshop#1]
after pip install cryptoshop with python 3.4 I got this import error, there is no a botan module in pypi

python3
Python 3.4.3 (default, Jun 20 2016, 14:47:04) 
[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptoshop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/__init__.py", line 26, in <module>
    from cryptoshop.cryptoshop import encryptfile
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/cryptoshop.py", line 56, in <module>
    from ._cascade_engine import encry_decry_cascade
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/_cascade_engine.py", line 27, in <module>
    from ._nonce_engine import generate_nonce_timestamp
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/_nonce_engine.py", line 39, in <module>
    import botan
ImportError: No module named 'botan'
>>> from crytpshop import encryptstring
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'crytpshop'
>>> from crytoshop import encryptstring
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'crytoshop'
>>> from cryptoshop import encryptstring
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/__init__.py", line 26, in <module>
    from cryptoshop.cryptoshop import encryptfile
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/cryptoshop.py", line 56, in <module>
    from ._cascade_engine import encry_decry_cascade
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/_cascade_engine.py", line 27, in <module>
    from ._nonce_engine import generate_nonce_timestamp
  File "/home/wmoreno/Proyectos/venv/lib64/python3.4/site-packages/cryptoshop/_nonce_engine.py", line 39, in <module>
    import botan
ImportError: No module named 'botan'

**Comment by Antidote1911** [comment]
you must install the latest development release of Botan (1.11.30). The Python Botan Wrapper is included. https://botan.randombit.net/#download

**Comment by williamjmorenor** [comment]
Thanks

**Comment by francoatmega** [comment]
SO, I have compiled, tested, and everything goes fine. But how I install botan module on python. There's a folder python36 on botan folder. How I do that.

**Comment by vjoao** [comment]
Did you solve this, @francoatmega ?

**Comment by fariqizwan** [comment]
botan lib will by default copied the file into /usr/local/lib/ after 'make install'
`
1) add /usr/local/lib into $PATH
2) find botan2.py in /usr/local/lib/python2.7/site-packages/
3) copy the file into python2/3 site-packages folder either main or virtualenv python site-packages folder or both
4) rename the file to botan.py
`
And now you can use cryptoshop! Hope this helps.
